apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argocd
spec:
  project: monitoring
  source:
    repoURL: https://github.com/InspireX96/kubeadm-deployment
    path: kube-prometheus/overlays/dev
    targetRevision: HEAD
    helm:
      valueFiles:
        - kube-prometheus-values.yaml
      releaseName: kube-prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
