apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: monitoring
spec:
  project: monitoring
  source:
    repoURL: https://github.com/InspireX96/kubeadm-deployment
    path: kube-prometheus/overlays/monitoring
    targetRevision: HEAD
    helm:
      chart:
        - 
      valueFiles:
        - kube-prometheus-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
