# https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/Chart.yaml
apiVersion: v2
name: kube-prometheus-stack
version: 0.1.0
dependencies:
- name: kube-prometheus-stack
  version: 20.0.1
  repository: https://prometheus-community.github.io/helm-charts
